
export const banks = [
  { value: "Nubank (Nu Pagamentos S.A.) - 260", label: "Nubank (Nu Pagamentos S.A.) - 260" },
  { value: "Bradesco - 237", label: "Bradesco - 237" },
  { value: "Banco do Brasil - 001", label: "Banco do Brasil - 001" },
  { value: "Caixa Econômica Federal (CEF) - 104", label: "Caixa Econômica Federal (CEF) - 104" },
  { value: "Itaú Unibanco - 341", label: "Itaú Unibanco - 341" },
  { value: "Santander Brasil - 033", label: "Santander Brasil - 033" },
  { value: "BTG Pactual - 208", label: "BTG Pactual - 208" },
  { value: "Banco Inter - 077", label: "Banco Inter - 077" },
  { value: "Banco Original - 212", label: "Banco Original - 212" },
  { value: "C6 Bank - 336", label: "C6 Bank - 336" },
  { value: "Banco Safra - 422", label: "Banco Safra - 422" },
  { value: "Banco Pan - 623", label: "Banco Pan - 623" },
  { value: "Banrisul - 041", label: "Banrisul - 041" },
  { value: "Sicoob - 756", label: "Sicoob - 756" },
  { value: "Sicredi - 748", label: "Sicredi - 748" },
  { value: "Banco Mercantil do Brasil - 389", label: "Banco Mercantil do Brasil - 389" },
  { value: "Banco Daycoval - 707", label: "Banco Daycoval - 707" },
  { value: "Banco BMG - 318", label: "Banco BMG - 318" },
  { value: "Banco Modal - 746", label: "Banco Modal - 746" },
  { value: "Banco BS2 - 218", label: "Banco BS2 - 218" },
  { value: "Banco Sofisa (Sofisa Direto) - 637", label: "Banco Sofisa (Sofisa Direto) - 637" },
  { value: "Banco Neon (via Banco Votorantim / BV) - 655", label: "Banco Neon (via Banco Votorantim / BV) - 655" },
  { value: "Banco XP - 348", label: "Banco XP - 348" },
]
